---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-image-updater
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.13.0
    chart: argocd-image-updater
    helm:
      releaseName: argocd-image-updater
      valueFiles:
      - $values/argocd-image-updater/values.yaml
  - repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

