---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    path: bitwarden_storage
  destination:
    server: https://kubernetes.default.svc
    namespace: bitwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

