---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
  - repoURL: https://charts.bitwarden.com/
    chart: self-host
    targetRevision: 2025.10.0
    helm:
      releaseName: bitwarden
      valueFiles:
      - $values/applications/security/bitwarden/values.yaml
  - repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: bitwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

