---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch-benchmark
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    chart: elasticsearch
    helm:
      releaseName: elasticsearch-benchmark
      valueFiles:
      - $values/elasticsearch-benchmark/values.yaml
  - repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: benchmark-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

