---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: excalidraw-storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    path: excalidraw
    directory:
      recurse: false
      include: "{postgresql.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: excalidraw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

