---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: excalidraw
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://pmoscode-helm.github.io/excalidraw/
    targetRevision: 0.1.1
    chart: excalidraw
    helm:
      releaseName: excalidraw
      valueFiles:
      - $values/excalidraw/values.yaml
  - repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: excalidraw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

