# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: kyverno-policies
#   namespace: argocd
#   annotations:
#     argocd.argoproj.io/sync-wave: "1"
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
#     targetRevision: main
#     path: kyverno-policies
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: kyverno
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - SkipDryRunOnMissingResource=true
#       - ServerSideApply=true

