---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-recurring-jobs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    path: .
    directory:
      recurse: false
      include: 'longhorn-recurring-jobs.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

