---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    path: longhorn
    directory:
      recurse: false
      include: "*.yaml"
      exclude: "Chart.yaml"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false

