---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 67.11.0
    chart: kube-prometheus-stack
    helm:
      releaseName: monitoring
      valueFiles:
      - $values/monitoring/values.yaml
  - repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    ref: values
  - repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    path: monitoring
    directory:
      recurse: false
      include: '{*-service.yaml,servicemonitor-*.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: false  # StatefulSets with PVCs - don't auto-delete
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /status
        - /spec/volumeName
        - /metadata/finalizers
