---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mssql
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
  - repoURL: https://microsoft.github.io/mssql-server-samples/
    chart: mssql
    targetRevision: 0.5.0
    helm:
      releaseName: mssql
      valueFiles:
      - $values/applications/databases/mssql/values.yaml
  - repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: bitwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
