---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://community-charts.github.io/helm-charts
    targetRevision: 1.15.18
    chart: n8n
    helm:
      releaseName: n8n
      valueFiles:
      - $values/n8n/values.yaml
  - repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: n8n
  syncPolicy:
    automated:
      prune: false  # Don't prune - has PVC
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /status
        - /spec/volumeName
        - /metadata/finalizers
