---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: navidrome
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://djjudas21.github.io/charts/
    targetRevision: 6.7.5
    chart: navidrome
    helm:
      releaseName: navidrome
      valueFiles:
      - $values/navidrome/values.yaml
  - repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: navidrome
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
