---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane-web-clusterip
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    path: .
    directory:
      recurse: false
      include: "plane-web-clusterip-service.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: plane
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

