---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://helm.plane.so/
    targetRevision: 1.4.0
    chart: plane-ce
    helm:
      releaseName: plane
      valueFiles:
      - $values/plane/values.yaml
  - repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: plane
  syncPolicy:
    automated:
      prune: false  # Has StatefulSets with PVCs - don't auto-delete
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  ignoreDifferences:
  - group: batch
    kind: Job
    jsonPointers:
    - /spec/template/metadata/annotations/timestamp
  - group: ""
    kind: PersistentVolumeClaim
    jsonPointers:
    - /status
    - /spec/volumeName
    - /metadata/finalizers
  - group: apps
    kind: Deployment
    jsonPointers:
    - /metadata/annotations/deployment.kubernetes.io~1revision  # Auto-generated by K8s
