---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-bitwarden-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    path: tailscale-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: bitwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

