---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-ingresses
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    path: tailscale-operator
    directory:
      recurse: false
      include: "*-ts-ingress.yaml"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

