---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    path: uptime-kuma
    helm:
      releaseName: uptime-kuma
      valueFiles:
      - $values/uptime-kuma/values.yaml
  - repoURL: https://github.com/rmsz005/sabkhi_lab_values.git
    targetRevision: main
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: ""
      kind: PersistentVolumeClaim
      jsonPointers:
        - /status
        - /spec/volumeName
        - /metadata/finalizers

